# Generated by Django 5.0.3 on 2026-04-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("background_url", models.URLField(blank=True, max_length=500)),
                ("position", models.IntegerField(db_index=True, default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_restricted", models.BooleanField(default=False)),
                ("discussion_count", models.IntegerField(default=0)),
                ("last_posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_posted_discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="discussions.discussion",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscussionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_tags",
                        to="discussions.discussion",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_tags",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "db_table": "discussion_tag",
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="tags_slug_c72f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["parent"], name="tags_parent__7fcc39_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["position"], name="tags_positio_894349_idx"),
        ),
        migrations.AddIndex(
            model_name="discussiontag",
            index=models.Index(
                fields=["discussion"], name="discussion__discuss_d30c2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussiontag",
            index=models.Index(fields=["tag"], name="discussion__tag_id_4f1793_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="discussiontag",
            unique_together={("discussion", "tag")},
        ),
    ]
