# Generated by Django 5.0.3 on 2026-04-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_posted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_post_id", models.IntegerField(blank=True, null=True)),
                ("last_post_number", models.IntegerField(blank=True, null=True)),
                ("comment_count", models.IntegerField(default=0)),
                ("participant_count", models.IntegerField(default=0)),
                ("first_post_id", models.IntegerField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_sticky", models.BooleanField(db_index=True, default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "discussions",
                "ordering": ["-is_sticky", "-last_posted_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscussionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_post_number", models.IntegerField(default=0)),
                ("is_subscribed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "discussion_user",
            },
        ),
    ]
