# Generated by Django 5.0.3 on 2026-04-04 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discussions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="hidden_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="last_posted_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_posted_discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussionuser",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_states",
                to="discussions.discussion",
            ),
        ),
        migrations.AddField(
            model_name="discussionuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(fields=["user"], name="discussions_user_id_4b0eee_idx"),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["created_at"], name="discussions_created_b92989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["last_posted_at"], name="discussions_last_po_1eb5b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(fields=["slug"], name="discussions_slug_00b0e3_idx"),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["is_sticky", "last_posted_at"],
                name="discussions_is_stic_305910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discussionuser",
            index=models.Index(
                fields=["discussion"], name="discussion__discuss_4635af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussionuser",
            index=models.Index(fields=["user"], name="discussion__user_id_f6be64_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="discussionuser",
            unique_together={("discussion", "user")},
        ),
    ]
