# Generated by Django 5.0.3 on 2026-04-04 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hidden_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postmentionsuser",
            name="mentions_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_in_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postmentionsuser",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="posts.post",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["discussion"], name="posts_discuss_49d427_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["user"], name="posts_user_id_05c508_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_created_060265_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["type"], name="posts_type_97ace5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("discussion", "number")},
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(fields=["post"], name="post_likes_post_id_c6421f_idx"),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(fields=["user"], name="post_likes_user_id_7d46ab_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user")},
        ),
        migrations.AddIndex(
            model_name="postmentionsuser",
            index=models.Index(fields=["post"], name="post_mentio_post_id_b5c7ae_idx"),
        ),
        migrations.AddIndex(
            model_name="postmentionsuser",
            index=models.Index(
                fields=["mentions_user"], name="post_mentio_mention_4f2ed3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmentionsuser",
            unique_together={("post", "mentions_user")},
        ),
    ]
